auth:
  api_key: put your api_key here
  api_secret_key: put your api_secret_key here

  access_token: put your access_token here
  access_token_secret: put your access_token_secret here

log_level: INFO

flow:
  repeat: true # repeat steps once they're complete
  max_total_following: 4500 # no users will be followed if you're already following this number or more
  steps:
    - random:
        options: # will choose a random step among all of these option. Any valid step can be an `option`, even nested `randoms`
          - follow_followers_of_others:
              max_to_follow: 100
              max_sources_to_pick: 3 # consider at most 3 random sources from the list of "others"
              others: # screen names of other accounts to follow followers from
                - list of twitter handlers

          - follow_followers_of_others:
              max_to_follow: 100
              max_sources_to_pick: -1 # consider all "others"
              others:
                - another of twitter handlers

    - follow_all_followers:
        max_to_follow: 200

    - unfollow_bad_friends:
        max_to_unfollow: 400

    - wait:
        seconds: 27
        minutes: 30
        hours: 0

    - wait_until_day:
        relative: tomorrow
